remote_theme: wet-boew/gcweb-jekyll
title: Training material to learn WCAG Success Criteria from Governement of Canada web presence perspective (GCWeb)

#
# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default
